### ISSUE TITLE
Support for DZIP

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/WebAlign#2]
Support for DZIP either natively or through the API hosted at: 
`https://tar-svc-test.apps.hbp.eu/`
There are two useful endpoints here.
The first is 
https://tar-svc-test.apps.hbp.eu/fakebucket/?url=
where url is equal to a folder containing many dzips. This will pretend to be a folder containing many DZI folders and for instance is natively compatible with miosdv. 
The second endpoint which may be of use is 
https://tar-svc-test.apps.hbp.eu/dzip/?dzipUrl=&fileName=
where dzip Url is the data proxy link to a dzip file and filename is the specific file you wish to request. (ie; a .dzi file or a jpeg/png file)

**Comment by Tevemadar** [comment]
Series creation offers DZIP pyramids from `.nesysWorkflowFiles/zippedPyramids/`, then WebAlign uses them.

**Comment by Majpuc** [comment]
Validated 21.06.2023
