### ISSUE TITLE
WebAlign registration file waln is not properly overwritten

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/WebAlign#22]
Test on 13/04/2023 11.00-12.00
Location: https://wiki.ebrains.eu/bin/view/Collabs/image-registration-and-analysis-demo/ 

When I change the registration and "save as" to overwrite the registration, this file is not overwritten even after clicking "yes".
If I reload WebAlign, the old file is the one that is opened.

**Comment by Tevemadar** [comment]
Approximatlely how old is the old file? Right now `my images.waln` has a file date `4/13/2023, 11:46:42 AM`, which is only 7-8 minutes older than this ticket (`Apr 13, 2023, 11:54 AM GMT+2`).

**Comment by Majpuc** [comment]
I don't know but I noticed that the alignment was off and wanted to correct it. Even if the file was overwritten, the new delineations are not visible. I tried several times.

**Comment by Tevemadar** [comment]
Perhaps the `Store` mechanism needs to be rethought.

**Comment by Tevemadar** [comment]
Firefox misbehaviour, fixed. Also for LocaliZoom/WebWarp.

**Comment by Majpuc** [comment]
Should the app be uninstalled and re-installed to see the effect of the change?

**Comment by Tevemadar** [comment]
~~It's related to cache in Firefox, it may have to be cleared.~~ The affected code can't be  cached, it should work immediately.

**Comment by Majpuc** [comment]
I can't make it work even after cache clearing. The files are saved but the new anchoring is not present. Same behavior with Firefox private window and with Edge. Maybe someone else in the team can try this out as well?

**Comment by Tevemadar** [comment]
Firefox-specific behaviour is fixed, feature request continues in another issue.

**Comment by Majpuc** [comment]
Closed 21.06.2023
