### ISSUE TITLE
KG series support

### ISSUE THREAD

**Issue by Tevemadar** [Neural-Systems-at-UIO/WebAlign#24]

**Comment by Tevemadar** [comment]
https://github.com/Neural-Systems-at-UIO/WebAlign/commit/103e96999390c8949cdcfc59fb21adb5b28583da for series in collab buckets. Gets both linear and nonlinear alignment data.

**Comment by Tevemadar** [comment]
https://github.com/Neural-Systems-at-UIO/WebAlign/commit/322e72784dbf8d85ea892c6bd21e2ba7c3711c34 supports the old image service too.

**Comment by Majpuc** [comment]
Validated 21.06.2023
