### ISSUE TITLE
webAlign wont show section until the level of tile that matches the screen resolution is reached

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/WebAlign#26]
webalign wont show any image until the level of tile for the window size has been reached (see image)
![image](https://github.com/Neural-Systems-at-UIO/WebAlign/assets/38996929/8975de63-dc4a-4361-a599-14eeafcf72d9)
If i make the window smaller the image will show since it can now be filled with a lower resolution of tile. In practice this removes much of the benefit of tiled images and makes the loading take quite a long time.

**Comment by Tevemadar** [comment]
Fixed in https://github.com/Neural-Systems-at-UIO/WebAlign/commit/7601ccac358342055cdffa08ba6bccb7eb26915f
