### ISSUE TITLE
may we please have all the anchorings filled by the propagation

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/WebAlign#30]
When there are empty anchorings it leads to a lot of difficulty downstream in pynutil since we may incomplete anchorings, and incomplete segmentations. It has the opportunity to silently fail not quantifying the full brain as people might expect.

**Comment by PolarBean** [comment]
Furthermore, since we no longer require exporting overlays for webnutil (which did output all the sections) this would make the behaviour consistent.

**Comment by Tevemadar** [comment]
Some of those difficulties may go away if pynutil considers including the propagation code from https://github.com/Tevemadar/QuickNII-extras/tree/master/Python
Fresh from the oven, with a brand new bug fix, and the capability to take section numbers from the `_s123` part of filenames (optionally existing `nr` field takes precedence).

**Comment by PolarBean** [comment]
oh thats very useful, also for DeepSlice. Thank you
