### ISSUE TITLE
license and copyright ?

### ISSUE THREAD

**Issue by lzehl** [Neural-Systems-at-UIO/WebAlign#34]
maybe it is on purpose but the README states the MIT license but the license file is missing from the repository. Is the license MIT ? and who is the copyright owner and what is the copyright year?

**Comment by Tevemadar** [comment]
Thanks, fixed in https://github.com/Neural-Systems-at-UIO/WebAlign/commit/92c64efb1b3a1d5046d4cb05b48979455eb52a4d
